#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/pi/catkinws/devel_isolated/hector_mapping:/home/pi/catkinws/devel_isolated/tf_conversions:/home/pi/catkinws/devel_isolated/laser_geometry:/home/pi/catkinws/devel_isolated/hector_trajectory_server:/home/pi/catkinws/devel_isolated/hector_map_server:/home/pi/catkinws/devel_isolated/hector_imu_tools:/home/pi/catkinws/devel_isolated/hector_imu_attitude_to_tf:/home/pi/catkinws/devel_isolated/tf:/home/pi/catkinws/devel_isolated/rplidar_ros:/home/pi/catkinws/devel_isolated/orocos_kinematics_dynamics:/home/pi/catkinws/devel_isolated/kdl_conversions:/home/pi/catkinws/devel_isolated/eigen_conversions:/home/pi/catkinws/devel_isolated/opencv_tests:/home/pi/catkinws/devel_isolated/image_geometry:/home/pi/catkinws/devel_isolated/hector_slam_launch:/home/pi/catkinws/devel_isolated/hector_slam:/home/pi/catkinws/devel_isolated/hector_geotiff_plugins:/home/pi/catkinws/devel_isolated/hector_geotiff:/home/pi/catkinws/devel_isolated/hector_nav_msgs:/home/pi/catkinws/devel_isolated/hector_marker_drawing:/home/pi/catkinws/devel_isolated/hector_compressed_map_transport:/home/pi/catkinws/devel_isolated/hector_map_tools:/home/pi/catkinws/devel_isolated/geometry:/home/pi/catkinws/devel_isolated/cv_bridge:/home/pi/catkinws/devel_isolated/angles:/home/pi/catkinws/devel:/opt/ros/indigo:/home/pi/catkinws/devel_isolated/python_orocos_kdl:/home/pi/catkinws/devel_isolated/orocos_kdl"
export CPATH="/home/pi/catkinws/devel_isolated/tf/include:/home/pi/catkinws/devel_isolated/hector_nav_msgs/include:/home/pi/catkinws/devel/include:/opt/ros/indigo/include:/home/pi/catkinws/devel_isolated/orocos_kdl/include"
export LD_LIBRARY_PATH="/home/pi/catkinws/devel_isolated/tf_conversions/lib:/home/pi/catkinws/devel_isolated/laser_geometry/lib:/home/pi/catkinws/devel_isolated/hector_trajectory_server/lib:/home/pi/catkinws/devel_isolated/hector_map_server/lib:/home/pi/catkinws/devel_isolated/hector_imu_tools/lib:/home/pi/catkinws/devel_isolated/hector_imu_attitude_to_tf/lib:/home/pi/catkinws/devel_isolated/tf/lib:/home/pi/catkinws/devel_isolated/rplidar_ros/lib:/home/pi/catkinws/devel_isolated/kdl_conversions/lib:/home/pi/catkinws/devel_isolated/eigen_conversions/lib:/home/pi/catkinws/devel_isolated/opencv_tests/lib:/home/pi/catkinws/devel_isolated/image_geometry/lib:/home/pi/catkinws/devel_isolated/hector_slam_launch/lib:/home/pi/catkinws/devel_isolated/hector_geotiff_plugins/lib:/home/pi/catkinws/devel_isolated/hector_geotiff/lib:/home/pi/catkinws/devel_isolated/hector_nav_msgs/lib:/home/pi/catkinws/devel_isolated/hector_marker_drawing/lib:/home/pi/catkinws/devel_isolated/hector_compressed_map_transport/lib:/home/pi/catkinws/devel_isolated/hector_map_tools/lib:/home/pi/catkinws/devel_isolated/cv_bridge/lib:/home/pi/catkinws/devel_isolated/angles/lib:/home/pi/catkinws/devel/lib:/opt/ros/indigo/lib:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib:/home/pi/catkinws/devel_isolated/orocos_kdl/lib"
export PKG_CONFIG_PATH="/home/pi/catkinws/devel_isolated/tf_conversions/lib/pkgconfig:/home/pi/catkinws/devel_isolated/laser_geometry/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_trajectory_server/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_map_server/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_imu_tools/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_imu_attitude_to_tf/lib/pkgconfig:/home/pi/catkinws/devel_isolated/tf/lib/pkgconfig:/home/pi/catkinws/devel_isolated/rplidar_ros/lib/pkgconfig:/home/pi/catkinws/devel_isolated/kdl_conversions/lib/pkgconfig:/home/pi/catkinws/devel_isolated/eigen_conversions/lib/pkgconfig:/home/pi/catkinws/devel_isolated/opencv_tests/lib/pkgconfig:/home/pi/catkinws/devel_isolated/image_geometry/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_slam_launch/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_geotiff_plugins/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_geotiff/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_nav_msgs/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_marker_drawing/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_compressed_map_transport/lib/pkgconfig:/home/pi/catkinws/devel_isolated/hector_map_tools/lib/pkgconfig:/home/pi/catkinws/devel_isolated/cv_bridge/lib/pkgconfig:/home/pi/catkinws/devel_isolated/angles/lib/pkgconfig:/home/pi/catkinws/devel/lib/pkgconfig:/opt/ros/indigo/lib/pkgconfig:/home/pi/catkinws/devel_isolated/orocos_kdl/lib/pkgconfig"
export PYTHONPATH="/home/pi/catkinws/devel_isolated/tf_conversions/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/laser_geometry/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/tf/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/image_geometry/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/hector_nav_msgs/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/cv_bridge/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/angles/lib/python2.7/dist-packages:/home/pi/catkinws/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib/python2.7/dist-packages"
export ROSLISP_PACKAGE_DIRECTORIES="/home/pi/catkinws/devel_isolated/hector_mapping/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/pi/catkinws/src/hector_slam/hector_mapping:$ROS_PACKAGE_PATH"