#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/pi/catkinws/devel_isolated/serial:/home/pi/catkinws/devel_isolated/vision_opencv:/home/pi/catkinws/devel_isolated/tf_conversions:/home/pi/catkinws/devel_isolated/laser_geometry:/home/pi/catkinws/devel_isolated/tf:/home/pi/catkinws/devel_isolated/rplidar_ros:/home/pi/catkinws/devel_isolated/orocos_kinematics_dynamics:/home/pi/catkinws/devel_isolated/kdl_conversions:/home/pi/catkinws/devel_isolated/eigen_conversions:/home/pi/catkinws/devel_isolated/opencv_tests:/home/pi/catkinws/devel_isolated/image_geometry:/home/pi/catkinws/devel_isolated/geometry:/home/pi/catkinws/devel_isolated/cv_bridge:/home/pi/catkinws/devel_isolated/angles:/home/pi/catkinws/devel:/opt/ros/indigo:/home/pi/catkinws/devel_isolated/python_orocos_kdl:/home/pi/catkinws/devel_isolated/python_orocos_kdl:/home/pi/catkinws/devel_isolated/orocos_kdl"
export LD_LIBRARY_PATH="/home/pi/catkinws/devel_isolated/serial/lib:/home/pi/catkinws/devel_isolated/tf_conversions/lib:/home/pi/catkinws/devel_isolated/laser_geometry/lib:/home/pi/catkinws/devel_isolated/tf/lib:/home/pi/catkinws/devel_isolated/rplidar_ros/lib:/home/pi/catkinws/devel_isolated/kdl_conversions/lib:/home/pi/catkinws/devel_isolated/eigen_conversions/lib:/home/pi/catkinws/devel_isolated/opencv_tests/lib:/home/pi/catkinws/devel_isolated/image_geometry/lib:/home/pi/catkinws/devel_isolated/cv_bridge/lib:/home/pi/catkinws/devel_isolated/angles/lib:/home/pi/catkinws/devel/lib:/opt/ros/indigo/lib:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib/arm-linux-gnueabihf:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib:/home/pi/catkinws/devel_isolated/orocos_kdl/lib"
export PATH="/home/pi/catkinws/devel_isolated/tf/bin:/opt/ros/indigo/bin:/home/pi/catkinws/devel_isolated/python_orocos_kdl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"
export PKG_CONFIG_PATH="/home/pi/catkinws/devel_isolated/serial/lib/pkgconfig:/home/pi/catkinws/devel_isolated/tf_conversions/lib/pkgconfig:/home/pi/catkinws/devel_isolated/laser_geometry/lib/pkgconfig:/home/pi/catkinws/devel_isolated/tf/lib/pkgconfig:/home/pi/catkinws/devel_isolated/rplidar_ros/lib/pkgconfig:/home/pi/catkinws/devel_isolated/kdl_conversions/lib/pkgconfig:/home/pi/catkinws/devel_isolated/eigen_conversions/lib/pkgconfig:/home/pi/catkinws/devel_isolated/opencv_tests/lib/pkgconfig:/home/pi/catkinws/devel_isolated/image_geometry/lib/pkgconfig:/home/pi/catkinws/devel_isolated/cv_bridge/lib/pkgconfig:/home/pi/catkinws/devel_isolated/angles/lib/pkgconfig:/home/pi/catkinws/devel/lib/pkgconfig:/opt/ros/indigo/lib/pkgconfig:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib/pkgconfig:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib/arm-linux-gnueabihf/pkgconfig:/home/pi/catkinws/devel_isolated/orocos_kdl/lib/pkgconfig"
export PYTHONPATH="/home/pi/catkinws/devel_isolated/tf_conversions/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/laser_geometry/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/tf/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/image_geometry/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/cv_bridge/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/angles/lib/python2.7/dist-packages:/home/pi/catkinws/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib/python2.7/dist-packages:/home/pi/catkinws/devel_isolated/python_orocos_kdl/lib/python2.7/dist-packages"