set(_CATKIN_CURRENT_PACKAGE "imu_node")
set(imu_node_VERSION "0.0.0")
set(imu_node_MAINTAINER "benjamin <benjamin@todo.todo>")
set(imu_node_PACKAGE_FORMAT "1")
set(imu_node_BUILD_DEPENDS "rospy" "roscpp" "tf" "std_msgs" "sensor_msgs" "geometry_msgs" "message_generation")
set(imu_node_BUILD_EXPORT_DEPENDS "rospy" "roscpp" "tf" "std_msgs" "sensor_msgs" "geometry_msgs" "message_runtime")
set(imu_node_BUILDTOOL_DEPENDS "catkin")
set(imu_node_BUILDTOOL_EXPORT_DEPENDS )
set(imu_node_EXEC_DEPENDS "rospy" "roscpp" "tf" "std_msgs" "sensor_msgs" "geometry_msgs" "message_runtime")
set(imu_node_RUN_DEPENDS "rospy" "roscpp" "tf" "std_msgs" "sensor_msgs" "geometry_msgs" "message_runtime")
set(imu_node_TEST_DEPENDS )
set(imu_node_DOC_DEPENDS )
set(imu_node_DEPRECATED "")